publisher_grasp_from_human_5direction_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 16
    trajectory_duration: 12

    grasp_direction: 1

    goal_names: ["pos0", "pos1", "pos2", "pos3", "pos4", "pos5"]

    #ZYZ Euler angle(d) and position(m)
    pos0: [-179.9, -90.0, 0.0, 0.45, -0.10, 0.55]  
    pos1: [-90.0, 90.0, 0.0, 0.6, -0.10, 0.55]     # left 
    #pos2: [-90.0, -90.0, 0.0, 0.6, -0.10, 0.55]     # right  #noooooooo
    pos2: [-179.9, -179.9, 0.0, 0.6, -0.10, 0.42]   # top
    pos3: [-179.9, -179.9, 0.0, 0.6, -0.10, 0.42]   # top
    pos4: [-89.9, 0.1, 0.0, 0.6, -0.10, 0.7]     # bottom
    pos5: [-179.9, -90.0, 0.0, 0.65, -0.10, 0.55]    # forward

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]
