publisher_inverse_kinematics_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 10
    moving_duration_time: 8

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6", "pos7", "pos8", "pos9", "pos10"]
    #ZYZ Euler angle(d) and position(m)
    pos1: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.30]  
    pos2: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.021]  #vertial grasp
    pos3: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.2] 
    #pos4: [-90.0, -120.0, 0.0, 0.45, 0.10, 0.2]   #facing left
    #pos5: [-90.0, -120.0, 0.0, 0.45, 0.10, 0.2]   #facing left down
    pos4: [0.0, 90.0, 180.0, 0.45, 0.2, 0.2]   #facing right
    pos5: [0.0, 90.0, 180.0, 0.45, 0.2, -0.01]     #facing right down
    pos6: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.2]
    #pos5: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.0215]   #vertial grasp
    #pos6: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.0215] 
    pos7: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.35]
    pos8: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.35]
    pos9: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.35]
    pos10: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.35]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]


publisher_inverse_kinematics_controller_grasp_laterally:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 8
    moving_duration_time: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6", "pos7", "pos8", "pos9", "pos10", "pos11", "pos12", "pos13", "pos14", "pos15", "pos16"]
    #ZYZ Euler angle(d) and position(m)
    pos1: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.30]  
    pos2: [0.0, 90.0, 0.0, 0.55, -0.10, 0.3]   #facing forward
    pos3: [0.0, 90.0, 0.0, 0.52, -0.10, 0.017]   #facing forward down, coke_can
    pos4: [0.0, 90.0, 0.0, 0.6, -0.10, 0.017]   #keep
    pos5: [0.0, 90.0, 0.0, 0.6, -0.10, 0.2]   #facing forward up
    pos6: [25.0, 90.0, -90.0, 0.54, 0.2, 0.2]   #facing left
    pos7: [25.0, 90.0, 180.0, 0.54, 0.2, 0.06]   #facing left down 2, coke_can
    pos8: [25.0, 90.0, 180.0, 0.54, 0.2, 0.005]   #keep
    pos9: [25.0, 90.0, 180.0, 0.54, 0.2, 0.2]   #facing left up 2
    pos10: [25.0, 90.0, -90.0, 0.54, 0.2, 0.2]    #rotate
    pos11: [-0.0, 90.0, 180.0, 0.6, -0.10, 0.2]   #move back
    pos12: [-0.0, 90.0, 180.0, 0.6, -0.10, 0.007]   #place
    pos13: [-0.0, 90.0, 180.0, 0.6, -0.10, 0.007]   
    pos14: [-0.0, 90.0, 180.0, 0.5, -0.15, 0.007]  
    pos15: [-0.0, 90.0, 180.0, 0.5, -0.15, 0.2]   #facing forward up
    pos16: [-90.0, 179.9, 0.0, 0.45, -0.10, 0.3]
    
    
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]






publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, -1.57, 0.785, 0.785, 0.785, 0.785]
    pos2: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]
    pos3: [0.0, -1.57, 0.0, 0.0, -0.785, 0.0]
    pos4: [0.0, -1.57, 0.0, 0.0, 0.0, 0.0]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]
